# Generated by Django 4.2.6 on 2023-10-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcates',
            name='img',
            field=models.ImageField(upload_to='FoodMenu'),
        ),
        migrations.AlterField(
            model_name='additems',
            name='img',
            field=models.ImageField(upload_to='item'),
        ),
    ]
