# Generated by Django 4.2.6 on 2023-10-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_alter_addcates_img_alter_additems_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaddress',
            name='addressId',
        ),
    ]
