# Generated by Django 4.2.6 on 2023-10-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_addorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addorderitem',
            old_name='user',
            new_name='username',
        ),
    ]
