# Generated by Django 4.2.6 on 2023-10-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_rename_user_addorderitem_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addorderitem',
            old_name='username',
            new_name='usernames',
        ),
    ]
