# Generated by Django 4.2.6 on 2023-10-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_rename_username_addorderitem_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addorderitem',
            old_name='usernames',
            new_name='user',
        ),
    ]
