# Generated by Django 4.2.6 on 2023-10-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_rename_usernames_addorderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addorderitem',
            name='user',
        ),
    ]
