# Generated by Django 4.2.6 on 2023-10-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_remove_addorderitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddOrderItem',
        ),
    ]
