# Generated by Django 4.2.6 on 2023-10-28 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BackEnd', '0011_addorderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOrderItem',
            new_name='Product',
        ),
    ]
