# Generated by Django 4.2.6 on 2023-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_rename_addorderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addressId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='itemId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='userId',
        ),
        migrations.DeleteModel(
            name='AddItems',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
