# Generated by Django 4.2.6 on 2023-10-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BackEnd', '0013_remove_product_addressid_remove_product_itemid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='item')),
                ('fname', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='BackEnd.addcates')),
            ],
        ),
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_sugg', models.TextField()),
                ('addressId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackEnd.addaddress')),
                ('itemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackEnd.product')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
