# Generated by Django 4.2.6 on 2023-10-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0014_product_addcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCates',
            new_name='AddCate',
        ),
    ]
