# Generated by Django 4.2.6 on 2023-11-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0016_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='addressId',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='any_sugg',
        ),
    ]
