# Generated by Django 4.2.6 on 2023-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0017_remove_addcart_addressid_remove_addcart_any_sugg'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
