# Generated by Django 4.2.6 on 2023-11-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0019_cart_cartitem_delete_addcart_cart_items_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
