# Generated by Django 4.2.7 on 2023-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0021_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='addaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='addaddress',
            name='anysuggession',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addaddress',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addaddress',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addaddress',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addaddress',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
