# Generated by Django 4.2.7 on 2023-11-29 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0031_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcate',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
